### ISSUE TITLE
Is it not support 'include'?

### ISSUE THREAD

**Issue by sheldonzf** [okonet/ejs-loader#13]

**Comment by okonet** [comment]
Are you looking for https://github.com/bazilio91/ejs-compiled-loader?

**Comment by axelpale** [comment]
To include other templates, passing template functions as parameters does the job. For example:

**index.js:**

    var mainTemplate = require('ejs!main.ejs');
    var hyperlinkTemplate = require('ejs!hyperlink.ejs');
    var renderedHtml = mainTemplate({ hyperlink: hyperlinkTemplate });

**main.ejs:**

    <h1><%= hyperlink({ name: 'Example', url: 'http://example.com' }) %></h1>

**hyperlink.ejs:**

    <a href="<%= url %>"><%= name %></a>

As a result, `renderedHtml` becomes a string `<h1><a href="http://example.com">Example</a></h1>`
