### ISSUE TITLE
Result template is only a string with a "module.exports = "

### ISSUE THREAD

**Issue by dinukadesilva** [okonet/ejs-loader#18]
Shouldn't this be a compiled source rather a string

```
"module.exports = function (data) {
var __t, __p = '';
__p += '<div>\r\n    <h1>Haaaaaaaai</h1>\r\n</div>';
return __p
}"
```

**Comment by dinukadesilva** [comment]
This happened since I had added the loaded both inline and in the webpack config as well. After removing the inline loader this is working fine. 

According to that, this behavior happens when the loader is being called more than once. 

Thanks

**Comment by protzi** [comment]
@dinukadesilva Could your provide some webpack config example  or what in my example wrong ?
I have this problem,

webpack 
```
    module:  {
      loaders: [
        {
          test:    /\.js$/,
          include: path.join(__dirname, "frontend"),
          loader:  'babel-loader',
          options: {
            presets: 'es2015',
            plugins: ['transform-decorators-legacy']
          }
        },
        { test: /\.ejs$/, loader: 'ejs-loader'}
      ]
    },
    plugins: [
      new webpack.NoErrorsPlugin(),
      new webpack.ProvidePlugin({
        _: "underscore"
      })
    ]
```
And got a result when require, const template = require('ejs!../sometemplate.ejs');

The result
```
module.exports = function (data) { var __t, __p = ''; __p += '
\n Hello product from template\n
'; return __p }

```
