### ISSUE TITLE
Escaping HTML Syntax error

### ISSUE THREAD

**Issue by florian-bd** [okonet/ejs-loader#28]
I am using the loader with the HtmlWebpackPlugin
If I don't use escaping it is working perfectly fine.
But as soon as I tried to use <%- %> I have issues.
First of all, I got an error "_ is not defined" so I added it a compile time

    new webpack.DefinePlugin({
        _: require('lodash')
    })

Now I get a weird error message: 

    var __t, __p = '', __e = ().escape, __j = Array.prototype.join;
                              ^
      SyntaxError: Unexpected token 

It seems that lodash is replaced by () instead of _

If try to use lodash manually to escape:

    <%= _.escape(myString) %>

I get the same error:

    ((__t = ( ().escape(compilation.assets[path].source()) )) == null ? '' : __t) +

**Comment by florian-bd** [comment]
I debugged the output of the loader and it's fine, the issue probably is in the HtmlWebpackPlugin

**Comment by florian-bd** [comment]
So I was using DefinePlugin instead of ProvidePlugin.
However we only want to define lodash at compile time, right?
Doesn't provide plugin have an impact on runtime?

**Comment by KnisterPeter** [comment]
No, to use ejs you need to have lodash or underscore at runtime available.

**Comment by KnisterPeter** [comment]
You are wrong. It is compiled during runtime. What you are looking for is this:
https://github.com/bazilio91/ejs-compiled-loader

**Comment by florian-bd** [comment]
Isn't it the purpose of a loader? To handle files during webpack compilation.
Anyway I am using this with HtmlWebpackPlugin so I'm pretty sure in my case it's not compiled at runtime :)

**Comment by KnisterPeter** [comment]
Be sure that this loader does not compile anything at compile time.
Anyway, good it works for you now.

**Comment by florian-bd** [comment]
Yeah I got it now, it generates lodash code which then, in my case, is executed by the HtmlWepackPlugin during the build.
So I tried the ejs-compiler-loader that you suggested, and indeed it works better for my case, since I don't have to provide lodash somehow.
Thanks for your help
