### ISSUE TITLE
how to process image.src in ejs?

### ISSUE THREAD

**Issue by jiajianrong** [okonet/ejs-loader#29]
I have index.js with code:

```
let tpl = require('./tpl.ejs');
let dom = tpl()
```

But tpl.ejs has `<image src="./a.jpg">`, so how to make it as jsx does? thanks.

**Comment by KnisterPeter** [comment]
@jiajianrong What do you mean? Do you want to rewrite the content of the src attribute? Thats not part of this loader.
To get around it add `./a.jpg` as value to your template and load it in your `index.js`. Then webpack will rewrite your path correctly.

**Comment by jiajianrong** [comment]
Thank you for so fast reply!

My tpl.ejs has an image tag, such as `<image src="./a.jpg">`, so after build I should be `<image src="https://mycdn/project/static/a.jpg">`

But now it still uses the relative path after build, as below:

```
module.exports = function (data) {
    var __t, __p = '';
    __p += '  <div class="box">\r\n<img class="fl" src="./img/pic1.png" alt="">..... </div>';
    return __p
}
```

Seems to me the webpack.config `output.publicPath` does not work for ejs (but it does work on normal html/js/css)

**Comment by jiajianrong** [comment]
Sorry it's not about ejs-loader.   Never mind.

I have to declare html-loader via  `require('html-loader!./tpl.ejs');` and problem was solved.  Thanks.
