### ISSUE TITLE
"not a loader" error in webpack ^4.6.0

### ISSUE THREAD

**Issue by yshterev** [okonet/ejs-loader#30]
```
node_modules\loader-runner\lib\loadLoader.js:35
throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");

Error: Module 'node_modules\ejs\lib\ejs.js' is not a loader (must have normal or pitch function)
```

Trying to use it like this:
```
new HtmlWebpackPlugin({
      inject: false,
      hash: true,
      template: '!!ejs!./views/index.ejs'
}),
```

Maybe this can help - https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by KnisterPeter** [comment]
The error you report is from loader-runner. That's not webpack I think.

**Comment by yshterev** [comment]
I did not use it properly - It works like this `template: '!!ejs-loader!./views/index.ejs'`
I thought the loader is not ported to webpack 4. I am closing this.
