### ISSUE TITLE
template(data) get a string?

### ISSUE THREAD

**Issue by websiteflash** [okonet/ejs-loader#6]
when i pass data to template by `template(data)`, i get a string like `module.exports = function anonymous(locals, escape, include, rethrow) {...`

but, i expect it return a html pice, can you tell me how to do?  thank you very mush.

**Comment by okonet** [comment]
Not sure why is it happening to you. What's in your template? And what data are you passing? Can you put a code sample with your config on github so I could reproduce?

**Comment by websiteflash** [comment]
this is my code:
```
var template = require('ejs!./tpl/index.ejs');
var data = {name: 'alice'};

template(data); // this retrun a string, like "module.exports=...." 
```

**Comment by okonet** [comment]
And what is in your ejs file? Does underscore  compiles it properly? Did you try without the loader?

Regards,
Andrey Okonetchnikov

**Comment by websiteflash** [comment]
https://github.com/okonet/ejs-loader/blob/master/index.js#L8
there return a string.

i use it with my `render` function like this, it works now.
```
var render = function(template, data){
        return eval(template({data: data}))({data: data});
    };
```
