### ISSUE TITLE
How to set templateSettings like in requireJS?

### ISSUE THREAD

**Issue by sww314** [okonet/ejs-loader#8]
I am working on moving a project from requireJS to webpack. Your loader has been a great help (thanks!).

I have some code that uses mustache style templates. They load fine do not render right. 
In the orginal requireJS file it set the templatesSettings:

>         templateSettings: {
>             evaluate : /\{\[([\s\S]+?)\]\}/g,
>             interpolate : /\{\{([\s\S]+?)\}\}/g
>         }

Is there a way to pass this configuration in in webpack.config.js?

**Comment by okonet** [comment]
You can use `query` to pass you options: https://github.com/okonet/ejs-loader/blob/master/index.js#L6-L7

Try something like this: 
```js
{
  test: /.../,
  loader: 'ejs-loader',
  query: {
    templateSettings: {
      evaluate : /\{\[([\s\S]+?)\]\}/g,
      interpolate : /\{\{([\s\S]+?)\}\}/g
    }
  }
}
```
